use_frameworks!

platform :ios, '10.0'

target 'XBSwiftBox_Example' do
  pod 'XBSwiftBox', :path => '../'

  target 'XBSwiftBox_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
